config/routes.rb
Rails.application.routes.draw do

  scope path_names: {new: 'solicitar', edit: 'efetuar'} do
    resources :ensalamentos do

      resources :sugestoes, only: [:index, :new, :create, :destroy], path_names: {new: 'novo'}

      collection do
        get 'solicitados'
        get 'abertos'
        get 'fechados'
      end
    end

    resources :reservas do
      collection do
        get 'solicitadas'
        get 'abertas'
        get 'fechadas'
      end
    end
  end

  scope path_names: {new: 'novo', edit: 'editar'} do
    scope 'ensalamentos/configuracao' do
      resources :predios, :salas, :periodos, except: :show
    end

    scope 'admin' do
      resources :usuarios, except: :show
    end

    resources :cursos, except: :show do
      resources :disciplinas, except: :show
    end

    resources :espacos
  end

  root 'index#index'

  get 'ensalamentos/relatorios/:periodo', controller: 'ensalamentos', action: 'relatorios', as: :relatorios

  get 'login', controller: 'index', action: 'login'
  post 'login', controller: 'index', action: 'logar'
  get 'logout', controller: 'index', action: 'logout'

  get '*path' => redirect('/')

end

app/models/curso.rb
class Curso < ActiveRecord::Base
  belongs_to :coordenador, class_name: 'Usuario'

  has_many :disciplinas, dependent: :restrict_with_error
  has_many :usuarios, dependent: :restrict_with_error

  validates :nome, presence: {message: '^Nome do curso não pode estar vazio.'}
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  belongs_to :curso
  belongs_to :professor, class_name: 'Usuario'

  has_many :ensalamentos

  validates :nome, presence: {message: '^O campo nome não pode estar vazio.'}
end

app/models/ensalamento.rb
class Ensalamento < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :sala
  belongs_to :periodo
  belongs_to :deferente, class_name: 'Usuario', inverse_of: :deferimentos
  belongs_to :solicitante, class_name: 'Usuario', inverse_of: :solicitacoes

  has_many :logs, as: :loggable
  has_many :sugestoes

  validates :disciplina_id, presence: {message: '^O campo disciplina não pode estar vazio.'}
  validates :alunos, presence: {message: '^A quantidade de alunos não pode estar vazia.'}
  validates :periodo_id, presence: {message: '^O campo período não pode estar vazio.'}
end

app/models/espaco.rb
class Espaco < ActiveRecord::Base
  has_many :reservas

  def to_s
    self.nome
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :loggable, polymorphic: true
end

app/models/periodo.rb
class Periodo < ActiveRecord::Base
  has_many :ensalamentos

  validates :nome, presence: {message: '^Nome do período não pode estar vazio.'}
end

app/models/predio.rb
class Predio < ActiveRecord::Base
  has_many :salas, dependent: :restrict_with_error

  validates :nome, presence: {message: '^Nome do prédio não pode estar vazio.'}
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :solicitante, class_name: 'Usuario'
  belongs_to :deferente, class_name: 'Usuario'
  belongs_to :espaco

  has_many :logs, as: :loggable
end

app/models/sala.rb
class Sala < ActiveRecord::Base
  belongs_to :predio

  has_many :ensalamentos
  has_many :sugestoes

  validates :nome, presence: {message: '^Nome da sala não pode estar vazio.'}
  validates :numero, presence: {message: '^Número da sala não pode estar vazio.'}
  validates :predio_id, presence: {message: '^É preciso que se selecione um prédio para a sala.'}
  validates :capacidade, presence: {message: '^Capacidade da sala não pode estar vazia.'}

  def self.ensalaveis(ensalamento)
    salas_usadas = Ensalamento.where('periodo_id = ? AND sala_id IS NOT NULL', ensalamento.periodo_id).pluck(:sala_id)
    where(
        'capacidade >= ? AND (id NOT IN (?) OR id = ?)',
        ensalamento.alunos,
        salas_usadas.any? ? salas_usadas : '',
        ensalamento.sala_id
    )
  end
end

app/models/sugestao.rb
class Sugestao < ActiveRecord::Base
  belongs_to :ensalamento
  belongs_to :sala

  has_many :logs, as: :loggable
end

app/models/tipo_usuario.rb
class TipoUsuario < ActiveRecord::Base
  has_many :usuarios, dependent: :restrict_with_error
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :tipo_usuario
  belongs_to :curso

  has_many :disciplinas, dependent: :restrict_with_error
  has_many :logs, dependent: :restrict_with_error
  has_many :deferimentos, class_name: 'Ensalamento', inverse_of: :deferente, foreign_key: 'deferente_id'
  has_many :solicitacoes, class_name: 'Ensalamento', inverse_of: :solicitante, foreign_key: 'solicitante_id'
  has_many :cursos

  has_many :reservas_solicitadas, class_name: 'Reserva', inverse_of: :solicitante
  has_many :reservas_efetuadas, class_name: 'Reserva', inverse_of: :deferente

  validates :nome, presence: {message: '^Nome do usuário não pode estar vazio.'}
  validates :cgu, presence: {message: '^Número do CGU não pode estar vazio.'}
  validates :curso_id, presence: {message: '^O campo curso não pode estar vazio para um coordenador de curso.'}, if: :coordenador?

  def coordenador?
    tipo_usuario_id == 2
  end
end

app/controllers/disciplinas_controller.rb
class DisciplinasController < ApplicationController
  before_action :set_disciplina, only: [:show, :edit, :update, :destroy]
  before_action :get_curso

  # GET /disciplinas
  # GET /disciplinas.json
  def index
    @disciplinas = @curso.disciplinas
  end

  # GET /disciplinas/1
  # GET /disciplinas/1.json
  def show
  end

  # GET /disciplinas/new
  def new
    @disciplina = Disciplina.new
  end

  # GET /disciplinas/1/edit
  def edit
  end

  # POST /disciplinas
  # POST /disciplinas.json
  def create
    @disciplina = @curso.disciplinas.create(disciplina_params)

    respond_to do |format|
      if @disciplina.save
        format.html { redirect_to curso_disciplinas_path, notice: 'Disciplina criada com sucesso.' }
        format.json { render :show, status: :created, location: @disciplina }
      else
        format.html { render :new }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplinas/1
  # PATCH/PUT /disciplinas/1.json
  def update
    respond_to do |format|
      if @disciplina.update(disciplina_params)
        format.html { redirect_to curso_disciplinas_path, notice: 'Disciplina atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @disciplina }
      else
        format.html { render :edit }
        format.json { render json: @disciplina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplinas/1
  # DELETE /disciplinas/1.json
  def destroy
    @disciplina.destroy
    respond_to do |format|
      format.html { redirect_to curso_disciplinas_path, notice: 'Disciplina removida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_disciplina
    @disciplina = Disciplina.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def disciplina_params
    params.require(:disciplina).permit(:nome, :curso_id, :professor_id)
  end

  def get_curso
    @curso = Curso.find(params[:curso_id]);
  end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/disciplinas_helper.rb
module DisciplinasHelper
end

app/helpers/espacos_helper.rb
module EspacosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/periodos_helper.rb
module PeriodosHelper
end

app/helpers/predios_helper.rb
module PrediosHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/sugestoes_helper.rb
module SugestoesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/disciplinas/_form.html.erb
<%= form_for [@curso, @disciplina] do |f| %>
    <% if @disciplina.errors.any? %>
        <div class="alert alert-danger fill">
          <h4><%= pluralize(@disciplina.errors.count, 'erro impediu', 'erros impediram') %>  esta disciplina de ser salva.</h4>

          <ul>
            <% @disciplina.errors.full_messages.each do |message| %>
                <li><small><%= message %></small></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <hr>
    <div class="row">
      <div class="col col-xs-12 form-group">
        <%= f.label 'Professor' %>
        <br>
        <%= f.collection_select(:professor_id, Usuario.all, :id, :nome, {:prompt => 'Selecione um professor.'}, {class: 'form-control'}) %>
      </div>
      <div class="col col-xs-12 form-group">
        <%= f.label :nome %>
        <br>
        <%= f.text_field :nome, class: 'form-control' %>
      </div>
    </div>
    <hr>
    <div class="actions" style="margin-bottom: 50px">
      <%= f.submit 'Salvar', class: 'btn btn-primary pull-left' %>
      <%= link_to 'Voltar', curso_disciplinas_path(@curso, @disciplina), class: 'btn btn-default pull-right' %>
    </div>
<% end %>

app/views/disciplinas/edit.html.erb
<h2>Nova disciplina para o curso de <strong><%= @curso.nome %></strong></h2>

<%= render 'form' %>

app/views/disciplinas/index.html.erb
<h2><i class="fa fa-pencil"></i> &nbsp;Disciplinas do curso de <strong><%= @curso.nome %></strong></h2>
<hr>
<% if notice %>
    <div class="alert alert-success fill">
      <button type="button" class="close" data-dismiss="alert">
        ×
      </button>
      <%= notice %>
    </div>
<% end %>
<p>
  <%= link_to 'Adicionar Disciplina', new_curso_disciplina_path(@curso), class: 'btn btn-primary' %>
</p>
<% if @disciplinas.any? %>
    <table class="table table-hover" style="margin-top: 10px">
      <thead>
      <tr>
        <th>Nome</th>
        <th>Professor</th>
        <th class="text-center" width="70"><i class="fa fa-cogs"></i></th>
      </tr>
      </thead>

      <tbody>
      <% @disciplinas.each do |disciplina| %>
          <tr>
            <td><%= disciplina.nome %></td>
            <td><%= disciplina.professor.nil? ? '--' : disciplina.professor.nome %></td>
            <td class="text-center">
              <div class="dropdown">
                <a class="btn btn-xs btn-default" data-toggle="dropdown">
                  <i class="fa fa-cog"></i><span class="caret"></span>
                </a>
                <ul class="dropdown-menu text-left">
                  <li role="presentation"><%= link_to edit_curso_disciplina_path(@curso, disciplina) do %>
                        <i class="fa fa-edit"></i> Editar
                    <% end %></li>
                  <li role="presentation"><%= link_to curso_disciplina_path(@curso, disciplina), method: :delete, data: {confirm: 'Deseja realmente remover esta disciplina?'} do %>
                        <i class="fa fa-trash-o"></i> Remover
                    <% end %></li>
                </ul>
              </div>


            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info">
      Parece que ainda não existe nenhuma disciplina cadastrada para este curso.
    </div>
<% end %>

app/views/disciplinas/new.html.erb
<h2>Nova disciplina para o curso de <strong><%= @curso.nome %></strong></h2>

<%= render 'form' %>

app/views/disciplinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @disciplina.nome %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @disciplina.curso %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @disciplina.professor %>
</p>

<%= link_to 'Edit', edit_disciplina_path(@disciplina) %> |
<%= link_to 'Back', disciplinas_path %>