config/routes.rb
Rails.application.routes.draw do

  scope path_names: {new: 'solicitar', edit: 'efetuar'} do
    resources :ensalamentos do

      resources :sugestoes, only: [:index, :new, :create, :destroy], path_names: {new: 'novo'}

      collection do
        get 'solicitados'
        get 'abertos'
        get 'fechados'
      end
    end

    resources :reservas do
      collection do
        get 'solicitadas'
        get 'abertas'
        get 'fechadas'
      end
    end
  end

  scope path_names: {new: 'novo', edit: 'editar'} do
    scope 'ensalamentos/configuracao' do
      resources :predios, :salas, :periodos, except: :show
    end

    scope 'admin' do
      resources :usuarios, except: :show
    end

    resources :cursos, except: :show do
      resources :disciplinas, except: :show
    end

    resources :espacos
  end

  root 'index#index'

  get 'ensalamentos/relatorios/:periodo', controller: 'ensalamentos', action: 'relatorios', as: :relatorios

  get 'login', controller: 'index', action: 'login'
  post 'login', controller: 'index', action: 'logar'
  get 'logout', controller: 'index', action: 'logout'

  get '*path' => redirect('/')

end

app/models/curso.rb
class Curso < ActiveRecord::Base
  belongs_to :coordenador, class_name: 'Usuario'

  has_many :disciplinas, dependent: :restrict_with_error
  has_many :usuarios, dependent: :restrict_with_error

  validates :nome, presence: {message: '^Nome do curso não pode estar vazio.'}
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  belongs_to :curso
  belongs_to :professor, class_name: 'Usuario'

  has_many :ensalamentos

  validates :nome, presence: {message: '^O campo nome não pode estar vazio.'}
end

app/models/ensalamento.rb
class Ensalamento < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :sala
  belongs_to :periodo
  belongs_to :deferente, class_name: 'Usuario', inverse_of: :deferimentos
  belongs_to :solicitante, class_name: 'Usuario', inverse_of: :solicitacoes

  has_many :logs, as: :loggable
  has_many :sugestoes

  validates :disciplina_id, presence: {message: '^O campo disciplina não pode estar vazio.'}
  validates :alunos, presence: {message: '^A quantidade de alunos não pode estar vazia.'}
  validates :periodo_id, presence: {message: '^O campo período não pode estar vazio.'}
end

app/models/espaco.rb
class Espaco < ActiveRecord::Base
  has_many :reservas

  def to_s
    self.nome
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :loggable, polymorphic: true
end

app/models/periodo.rb
class Periodo < ActiveRecord::Base
  has_many :ensalamentos

  validates :nome, presence: {message: '^Nome do período não pode estar vazio.'}
end

app/models/predio.rb
class Predio < ActiveRecord::Base
  has_many :salas, dependent: :restrict_with_error

  validates :nome, presence: {message: '^Nome do prédio não pode estar vazio.'}
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :solicitante, class_name: 'Usuario'
  belongs_to :deferente, class_name: 'Usuario'
  belongs_to :espaco

  has_many :logs, as: :loggable
end

app/models/sala.rb
class Sala < ActiveRecord::Base
  belongs_to :predio

  has_many :ensalamentos
  has_many :sugestoes

  validates :nome, presence: {message: '^Nome da sala não pode estar vazio.'}
  validates :numero, presence: {message: '^Número da sala não pode estar vazio.'}
  validates :predio_id, presence: {message: '^É preciso que se selecione um prédio para a sala.'}
  validates :capacidade, presence: {message: '^Capacidade da sala não pode estar vazia.'}

  def self.ensalaveis(ensalamento)
    salas_usadas = Ensalamento.where('periodo_id = ? AND sala_id IS NOT NULL', ensalamento.periodo_id).pluck(:sala_id)
    where(
        'capacidade >= ? AND (id NOT IN (?) OR id = ?)',
        ensalamento.alunos,
        salas_usadas.any? ? salas_usadas : '',
        ensalamento.sala_id
    )
  end
end

app/models/sugestao.rb
class Sugestao < ActiveRecord::Base
  belongs_to :ensalamento
  belongs_to :sala

  has_many :logs, as: :loggable
end

app/models/tipo_usuario.rb
class TipoUsuario < ActiveRecord::Base
  has_many :usuarios, dependent: :restrict_with_error
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :tipo_usuario
  belongs_to :curso

  has_many :disciplinas, dependent: :restrict_with_error
  has_many :logs, dependent: :restrict_with_error
  has_many :deferimentos, class_name: 'Ensalamento', inverse_of: :deferente, foreign_key: 'deferente_id'
  has_many :solicitacoes, class_name: 'Ensalamento', inverse_of: :solicitante, foreign_key: 'solicitante_id'
  has_many :cursos

  has_many :reservas_solicitadas, class_name: 'Reserva', inverse_of: :solicitante
  has_many :reservas_efetuadas, class_name: 'Reserva', inverse_of: :deferente

  validates :nome, presence: {message: '^Nome do usuário não pode estar vazio.'}
  validates :cgu, presence: {message: '^Número do CGU não pode estar vazio.'}
  validates :curso_id, presence: {message: '^O campo curso não pode estar vazio para um coordenador de curso.'}, if: :coordenador?

  def coordenador?
    tipo_usuario_id == 2
  end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/espacos_helper.rb
module EspacosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/periodos_helper.rb
module PeriodosHelper
end

app/helpers/predios_helper.rb
module PrediosHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/index/index.erb
<h2 style="margin: 0"><i class="fa fa-info-circle"></i> &nbspOlá, <strong><%= @activeUser.nome %></strong>.</h2>
<hr>
<div class="row" style="margin-top: 20px">
    <% if @activeUser.tipo_usuario_id.in? [4, 5] %>
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">Relatórios de ensalamentos.</h4>
                </div>
                <div class="panel-body">
                    <% if @periodos.any? %>
                        <table class="table table-hover" style="margin-top: 10px">
                            <thead>
                            <tr>
                                <th>Periodo</th>
                                <th class="text-center" width="160"><i class="fa fa-cogs"></i></th>
                            </tr>
                            </thead>

                            <tbody>
                            <% @periodos.each do |periodo| %>
                                <tr>
                                    <td><%= periodo.nome %></td>
                                    <td class="text-center">
                                        <%= link_to relatorios_path(periodo.id), class: 'btn btn-xs btn-info' do %>
                                            <i class="fa fa-download"></i> Baixar relatório.
                                        <% end %>
                                    </td>
                                </tr>
                            <% end %>
                            </tbody>
                        </table>
                    <% else %>
                        <div class="alert alert-info">
                            Parece que ainda não existe nenhum período cadastrado.
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    <% end %>
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">Reservas.</h4>
            </div>
            <div class="panel-body">
                <div class="fullCallendar"></div>
            </div>
        </div>
    </div>
    <script>
        $('.fullCallendar').fullCalendar({
            lang: 'es',
            monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
                'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
            buttonText: {
                today: 'hoje',
                month: 'mês',
                week: 'semana',
                day: 'dia'
            },
            dayNames: ['Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira',
                'Quinta-feira', 'Sexta-feira', 'Sábado'],
            defaultDate: '<%= Time.now.strftime('%Y-%m-%dT%H:%M:%S') %>',
            dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
            events: [
                <% @reservas.each do |reserva| %>
                {
                    title: '<%= reserva.espaco.nome %>',
                    start: '<%= reserva.inicio.strftime('%Y-%m-%dT%H:%M:%S') %>',
                    end: '<%= reserva.fim.strftime('%Y-%m-%dT%H:%M:%S') %>',
                    allDay: false
                },
                <% end %>
            ],
            timeFormat: 'dd/MM/yyyy HH:mm { - dd/MM/yyyy HH:mm}\n'
        });
    </script>
</div>

app/views/index/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <!--<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>-->
  <!--<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">-->
  <title>SYSCEE</title>
  <link href="/assets/bootstrap/css/bootstrap.css" rel="stylesheet">
  <link href="/assets/css/styles.css" rel="stylesheet">
  <!--[if lt IE 9]>
  <script src="/assets/js/html5shiv.js"></script>
  <script src="/assets/js/respond.min.js"></script>
  <![endif]-->
</head>
<body>
<section class="login">
  <div class="login-panel" style="height: <%= notice ? '260' : '200' %>px">
    <% if notice %>
        <div class="alert alert-warning">
          <p><%= notice %></p>
        </div>
    <% end %>
    <h3 class="text-muted">Login</h3>

    <%= form_for :login do |f| %>
        <%= f.text_field :cgu, class: 'form-control', placeholder: 'CGU' %>

        <div class="input-group">
          <%= f.password_field :senha, class: 'form-control', placeholder: 'Senha' %>
          <span class="input-group-btn">
				        <%= f.submit 'Entrar', class: 'btn btn-lg btn-default' %>
				      </span>
        </div>
    <% end %>
  </div>
</section>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script>
    $('.login-panel').fadeIn(800);
    $(".login").backstretch("/assets/img/big/1.jpg");
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>SYSCEE</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
<nav class="sidenav left" role="navigation">
    <ul class="menu">
        <li class="user">
            <div class="content">
                <img height="87" src="/img/sysce_logo.png" alt="">
                <br>

                <div>
                    <small>Sistema de Controle de Equipamentos e Espaços</small>
                </div>
                </p>
            </div>
        </li>
        <li>
            <%= link_to root_path do %>
                Home
                <div>
                    <img src="/assets/img/icons/desktop.png" alt="">
                </div>
            <% end %>
        </li>
        <% if @activeUser.tipo_usuario_id.in? [2, 4, 5] %>
            <li>
                <a>
                    Ensalamentos
                    <div>
                        <img src="/assets/img/icons/directions.png" alt="">
                    </div>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a class="back"><i class="fa fa-angle-left"></i> Voltar</a></li>
                    <% if @activeUser.tipo_usuario_id.in? [4, 5] %>
                        <li>
                            <a>Configurações</a>
                            <ul class="dropdown-menu second" role="menu">
                                <li><a class="back"><i class="fa fa-angle-left"></i> Voltar</a></li>
                                <li><%= link_to 'Períodos', periodos_path %></li>
                                <li><%= link_to 'Prédios', predios_path %></li>
                                <li><%= link_to 'Salas', salas_path %></li>
                            </ul>
                        </li>
                        <li>
                            <%= link_to 'Ensalamentos fechados', ensalamentos_path %>
                        </li>
                    <% end %>
                    <% if @activeUser.tipo_usuario_id == 4 %>
                        <li>
                            <%= link_to abertos_ensalamentos_path do %>
                                Ensalamentos em aberto
                                (<%= Ensalamento.where('final = false').where('ativo = true').count %>)
                            <% end %>
                        </li>
                        <li>
                            <%= link_to 'Ensalamentos fechados', fechados_ensalamentos_path %>
                        </li>
                    <% end %>
                    <% if @activeUser.tipo_usuario_id == 2 %>
                        <li>
                            <%= link_to 'Solicitar ensalamento', new_ensalamento_path %>
                        </li>
                        <li>
                            <%= link_to 'Ensalamentos solicitados', solicitados_ensalamentos_path %>
                        </li>
                    <% end %>
                </ul>
            </li>
        <% end %>
        <% if @activeUser.tipo_usuario_id.in? [2, 4, 5] %>
            <li>
                <%= link_to cursos_path do %>
                    Cursos
                    <div>
                        <img src="/assets/img/icons/hat.png" alt="">
                    </div>
                <% end %>
            </li>
        <% end %>
        <% if @activeUser.tipo_usuario_id.in? [3, 5] %>
            <li>
                <%= link_to espacos_path do %>
                    Espaços
                    <div>
                        <img src="/assets/img/icons/home.png" alt="">
                    </div>
                <% end %>
            </li>
        <% end %>
        <li>
            <a>
                Reservas
                <div>
                    <img src="/assets/img/icons/note.png" alt="">
                </div>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a class="back"><i class="fa fa-angle-left"></i> Voltar</a></li>
                <% if @activeUser.tipo_usuario_id.in? [3, 5] %>
                    <li>
                        <%= link_to abertas_reservas_path do %>
                            Reservas em aberto
                            (<%= Reserva.where('status = 1').count %>)
                        <% end %>
                    </li>
                    <li>
                        <%= link_to 'Reservas fechadas', fechadas_reservas_path %>
                    </li>
                <% end %>
                <li>
                    <%= link_to 'Solicitar Reserva', new_reserva_path %>
                </li>
                <li>
                    <%= link_to 'Reservas solicitadas', solicitadas_reservas_path %>
                </li>
            </ul>
        </li>
        <% if @activeUser.tipo_usuario_id == 5 %>
            <li>
                <%= link_to usuarios_path do %>
                    Usuários
                    <div>
                        <img src="/assets/img/icons/users.png" alt="">
                    </div>
                <% end %>
            </li>
        <% end %>
        <li class="logout">
            <%= link_to logout_path do %>
                Logout
                <div>
                    <img src="/assets/img/icons/off.png" alt="">
                </div>
            <% end %>
        </li>
    </ul>
</nav>
<div class="overlay"></div>
<div class="controlshint"><img src="/assets/img/swipe.png" alt="Menu Help"></div>
<section class="wrap">
    <div class="container">
        <div class="well main" style="display:none;">
            <%= yield %>
        </div>
    </div>
</section>
<script type="text/javascript">
    $(document).bind("mobileinit", function () {
        $.extend($.mobile, {autoInitializePage: false})
    });
</script>
<script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
</body>
</html>