config/routes.rb
Rails.application.routes.draw do

  scope path_names: {new: 'solicitar', edit: 'efetuar'} do
    resources :ensalamentos do

      resources :sugestoes, only: [:index, :new, :create, :destroy], path_names: {new: 'novo'}

      collection do
        get 'solicitados'
        get 'abertos'
        get 'fechados'
      end
    end

    resources :reservas do
      collection do
        get 'solicitadas'
        get 'abertas'
        get 'fechadas'
      end
    end
  end

  scope path_names: {new: 'novo', edit: 'editar'} do
    scope 'ensalamentos/configuracao' do
      resources :predios, :salas, :periodos, except: :show
    end

    scope 'admin' do
      resources :usuarios, except: :show
    end

    resources :cursos, except: :show do
      resources :disciplinas, except: :show
    end

    resources :espacos
  end

  root 'index#index'

  get 'ensalamentos/relatorios/:periodo', controller: 'ensalamentos', action: 'relatorios', as: :relatorios

  get 'login', controller: 'index', action: 'login'
  post 'login', controller: 'index', action: 'logar'
  get 'logout', controller: 'index', action: 'logout'

  get '*path' => redirect('/')

end

app/models/ensalamento.rb
class Ensalamento < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :sala
  belongs_to :periodo
  belongs_to :deferente, class_name: 'Usuario', inverse_of: :deferimentos
  belongs_to :solicitante, class_name: 'Usuario', inverse_of: :solicitacoes

  has_many :logs, as: :loggable
  has_many :sugestoes

  validates :disciplina_id, presence: {message: '^O campo disciplina não pode estar vazio.'}
  validates :alunos, presence: {message: '^A quantidade de alunos não pode estar vazia.'}
  validates :periodo_id, presence: {message: '^O campo período não pode estar vazio.'}
end

app/controllers/ensalamentos_controller.rb
class EnsalamentosController < ApplicationController
  before_action :check_acesso
  before_action :set_ensalamento, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [5]

    @ensalamentos = Ensalamento.all
  end

  def solicitados
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [2]

    @ensalamentos = @activeUser.solicitacoes.where('ativo = true')
  end

  def abertos
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [4]

    @ensalamentos = Ensalamento.where('final = false').where('ativo = true')
  end

  def fechados
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [4]

    @ensalamentos = Ensalamento.where('final = true').where('ativo = true')
  end

  def relatorios
    @periodo = Periodo.find params[:periodo]
    @ensalamentos = Ensalamento.find_by_periodo_id @periodo.id

    pdf = RelatorioEnsalamentos.new(@ensalamentos, @periodo)
    send_data pdf.render, filename: "Ensalamentos do periodo #{@periodo.nome}.pdf", type: 'application/pdf'
  end

# GET /ensalamentos/1
# GET /ensalamentos/1.json
  def show
    @logs = @ensalamento.logs
    @ensalamento.sugestoes.each do |sugestao|
      @logs << sugestao.logs
    end
  end

# GET /ensalamentos/new
  def new
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [2]

    @ensalamento = Ensalamento.new
  end

# GET /ensalamentos/1/edit
  def edit
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [4]
  end

# POST /ensalamentos
# POST /ensalamentos.json
  def create
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [2]

    @ensalamento = Ensalamento.new(ensalamento_params)
    @ensalamento.solicitante = @activeUser

    respond_to do |format|
      if @ensalamento.save
        @ensalamento.logs.create usuario: @activeUser, descricao: "Ensalamento solicitado para a disciplina de #{@ensalamento.disciplina.nome} com #{@ensalamento.alunos} alunos."
        format.html { redirect_to solicitados_ensalamentos_path, notice: 'Ensalamento solicitado com sucesso.' }
        format.json { render :show, status: :created, location: @ensalamento }
      else
        format.html { render :new }
        format.json { render json: @ensalamento.errors, status: :unprocessable_entity }
      end
    end
  end

# PATCH/PUT /ensalamentos/1
# PATCH/PUT /ensalamentos/1.json
  def update
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [4]

    respond_to do |format|
      if @ensalamento.sala.nil? and !ensalamento_params[:sala_id].nil?
        efetuar = true
        @ensalamento.final = true
        @ensalamento.deferente = @activeuser
      end
      if @ensalamento.update(ensalamento_params)
        if efetuar
          @ensalamento.logs.create({usuario: @activeUser, descricao: "Ensalamento efetuado para a sala #{@ensalamento.sala.nome}."})
          format.html { redirect_to abertos_ensalamentos_path, notice: 'Ensalamento efetuado com sucesso.' }
        else
          @ensalamento.logs.create({usuario: @activeUser, descricao: "Ensalamento realocado para a sala #{@ensalamento.sala.nome}."})
          format.html { redirect_to fechados_ensalamentos_path, notice: 'Ensalamento realocado com sucesso.' }
        end
        format.json { render :show, status: :ok, location: @ensalamento }
      else
        format.html { render :edit }
        format.json { render json: @ensalamento.errors, status: :unprocessable_entity }
      end
    end
  end

# DELETE /ensalamentos/1
# DELETE /ensalamentos/1.json
  def destroy
    @ensalamento.ativo = false unless @ensalamento.final

    @ensalamento.save
    @ensalamento.logs.create usuario: @activeUser, descricao: 'Ensalamento removido.'

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Ensalamento removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_ensalamento
    @ensalamento = Ensalamento.find(params[:id])

    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [4, 5] or @ensalamento.solicitante == @activeUser
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def ensalamento_params
    params.require(:ensalamento).permit(:disciplina_id, :sala_id, :periodo_id, :alunos, :final)
  end

  def check_acesso
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [2, 4, 5]
  end

end

app/helpers/ensalamentos_helper.rb
module EnsalamentosHelper
end

app/views/ensalamentos/_form.html.erb
<%= form_for(@ensalamento) do |f| %>
    <% if @ensalamento.errors.any? %>
        <div class="alert alert-danger fill">
          <h4><%= pluralize(@ensalamento.errors.count, 'erro impediu', 'erros impediram') %> este ensalamento de ser
            salvo.</h4>

          <ul>
            <% @ensalamento.errors.full_messages.each do |message| %>
                <li>
                  <small><%= message %></small>
                </li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <hr>
    <% if @ensalamento.new_record? %>
        <div class="row">
          <div class="col col-xs-6 form-group">
            <%= f.label 'Disciplina' %>
            <br>
            <%= f.collection_select(:disciplina_id, Disciplina.where('curso_id = ?', @activeUser.curso_id), :id, :nome, {:prompt => 'Selecione uma disciplina'}, {class: 'select2'}) %>
          </div>
        </div>
        <div class="row">
          <div class="col col-xs-6 form-group">
            <%= f.label 'Período' %>
            <br>
            <%= f.collection_select(:periodo_id, Periodo.all, :id, :nome, {:prompt => 'Selecione um período'}, {class: 'form-control'}) %>
          </div>
          <div class="col col-xs-6 form-group ">
            <%= f.label 'Quantidade de alunos' %>
            <br>
            <%= f.number_field :alunos, class: 'form-control', min: 0 %>
          </div>
        </div>
    <% else %>
        <div class="row">
          <div class="panel panel-info col-xs-12 col-md-6" style="margin: 15px">
            <div class="panel-heading">
              <h3 class="panel-title">Dados do ensalamento </h3>
            </div>
            <div class="panel-body">
              <dl>
                <dt>Período</dt>
                <dd><%= @ensalamento.periodo.nome %></dd>
                <br>
                <dt>Disciplina</dt>
                <dd><%= @ensalamento.disciplina.nome %> (<%= @ensalamento.disciplina.curso.nome %>)</dd>
                <br>
                <dt>Quantidade de alunos</dt>
                <dd><%= @ensalamento.alunos %></dd>
              </dl>
            </div>
          </div>
          <div class="panel panel-info col-xs-12 col-md-5" style="margin: 15px">
            <div class="panel-heading">
              <h3 class="panel-title">Sugestões </h3>
            </div>
            <div class="panel-body">
              <% if @ensalamento.sugestoes.any? %>
                  <ul>
                    <% @ensalamento.sugestoes.each do |sugestao| %>
                        <li><%= sugestao.sala.nome %></li>
                    <% end %>
                  </ul>
              <% else %>
                  <div class="alert alert-info fill">
                    <p>Parece que nenhuma sugestão foi feita a este ensalamento.</p>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 form-group">
            <%= f.label 'Sala' %>
            <br>
            <%= f.collection_select(:sala_id, Sala.ensalaveis(@ensalamento), :id, lambda {|s| "#{s.nome} | Capacidade: #{s.capacidade}"}, {:prompt => 'Selecione uma sala.'}, {class: 'select2'}) %>
          </div>
        </div>
    <% end %>
    <hr>
    <div class="actions" style="margin-bottom: 50px">
      <%= f.submit @ensalamento.new_record? ? 'Solicitar' : 'Efetuar', class: 'btn btn-primary pull-left' %>
      <%= link_to 'Voltar', 'javascript:void(0)', class: 'btn btn-default pull-right', onclick: 'history.go(-1)' %>
    </div>
<% end %>

app/views/ensalamentos/abertos.html.erb
<h2><i class="fa fa-compass"></i> &nbsp;Ensalamentos em aberto</h2>
<hr>
<% if notice %>
    <div class="alert alert-success fill">
      <button type="button" class="close" data-dismiss="alert">
        ×
      </button>
      <%= notice %>
    </div>
<% end %>
<% if @ensalamentos.any? %>
    <table class="table table-hover" style="margin-top: 10px">
      <thead>
      <tr>
        <th>Perídodo</th>
        <th>Disciplina</th>
        <th width="140">Qtd. de Alunos</th>
        <th class="text-center" width="70"><i class="fa fa-cogs"></i></th>
      </tr>
      </thead>

      <tbody>
      <% @ensalamentos.each do |ensalamento| %>
          <tr>
            <td><%= ensalamento.periodo.nome %></td>
            <td><%= ensalamento.disciplina.nome %></td>
            <td class="text-center"><%= ensalamento.alunos %></td>
            <td class="text-center">
              <div class="dropdown">
                <a class="btn btn-xs btn-default" data-toggle="dropdown">
                  <i class="fa fa-cog"></i><span class="caret"></span>
                </a>
                <ul class="dropdown-menu text-left">
                  <li role="presentation"><%= link_to ensalamento_path(ensalamento) do %>
                        <i class="fa fa-folder-open-o"></i> Detalhes
                    <% end %></li>
                  <li role="presentation"><%= link_to edit_ensalamento_path(ensalamento) do %>
                        <i class="fa fa-map-marker"></i> Efetuar
                    <% end %></li>
                </ul>
              </div>


            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info">
      Parece que nenhum ensalamento foi solicitado ainda.
    </div>
<% end %>

app/views/ensalamentos/edit.html.erb
<h2>Efetuando ensalamento</h2>

<%= render 'form' %>

app/views/ensalamentos/fechados.html.erb
<h2><i class="fa fa-compass"></i> &nbsp;Ensalamentos fechados</h2>
<hr>
<% if notice %>
    <div class="alert alert-success fill">
      <button type="button" class="close" data-dismiss="alert">
        ×
      </button>
      <%= notice %>
    </div>
<% end %>
<% if @ensalamentos.any? %>
    <table class="table table-hover" style="margin-top: 10px">
      <thead>
      <tr>
        <th>Perídodo</th>
        <th>Disciplina</th>
        <th width="140">Qtd. de Alunos</th>
        <th>Sala</th>
        <th class="text-center" width="70"><i class="fa fa-cogs"></i></th>
      </tr>
      </thead>

      <tbody>
      <% @ensalamentos.each do |ensalamento| %>
          <tr>
            <td><%= ensalamento.periodo.nome %></td>
            <td><%= ensalamento.disciplina.nome %></td>
            <td class="text-center"><%= ensalamento.alunos %></td>
            <td class="text-center"><%= ensalamento.sala ? ensalamento.sala.nome : '--' %></td>
            <td class="text-center">
              <div class="dropdown">
                <a class="btn btn-xs btn-default" data-toggle="dropdown">
                  <i class="fa fa-cog"></i><span class="caret"></span>
                </a>
                <ul class="dropdown-menu text-left">
                  <li role="presentation"><%= link_to ensalamento_path(ensalamento) do %>
                        <i class="fa fa-folder-open-o"></i> Detalhes
                    <% end %></li>
                  <li role="presentation"><%= link_to edit_ensalamento_path(ensalamento) do %>
                        <i class="fa fa-map-marker"></i> Realocar
                    <% end %></li>
                </ul>
              </div>


            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info">
      Parece que nenhum ensalamento foi efetuado ainda.
    </div>
<% end %>

app/views/ensalamentos/new.html.erb
<h2>Solicitar ensalamento</h2>

<%= render 'form' %>

app/views/ensalamentos/show.html.erb
<h2>Detalhes do ensalamento</h2>

<div class="row">
  <div class="panel panel-info col-xs-12 col-md-6" style="margin: 15px">
    <div class="panel-heading">
      <h3 class="panel-title">Dados </h3>
    </div>
    <div class="panel-body">
      <dl>
        <dt>Período</dt>
        <dd><%= @ensalamento.periodo.nome %></dd>
        <br>
        <dt>Disciplina</dt>
        <dd><%= @ensalamento.disciplina.nome %> (<%= @ensalamento.disciplina.curso.nome %>)</dd>
        <br>
        <dt>Quantidade de alunos</dt>
        <dd><%= @ensalamento.alunos %></dd>
      </dl>
    </div>
  </div>
  <div class="panel panel-info col-xs-12 col-md-5" style="margin: 15px">
    <div class="panel-heading">
      <h3 class="panel-title">Sugestões </h3>
    </div>
    <div class="panel-body">
      <% if @ensalamento.sugestoes.any? %>
          <ul>
            <% @ensalamento.sugestoes.each do |sugestao| %>
                <li><%= sugestao.sala.nome %></li>
            <% end %>
          </ul>
      <% else %>
          <div class="alert alert-info fill">
            <p>Parece que nenhuma sugestão foi feita a este ensalamento.</p>
          </div>
      <% end %>
    </div>
  </div>
  <div class="panel panel-info col-xs-12 col-md-6" style="margin: 15px">
    <div class="panel-heading">
      <h3 class="panel-title">Atualizações </h3>
    </div>
    <div class="panel-body">
      <div style="overflow: auto; max-height: 300px;">
        <% if @logs.any? %>
            <ul>
              <% @logs.each do |log| %>
                  <dl>
                    <dt>Usuário</dt>
                    <dd><%= log.usuario.nome %></dd>
                    <dt>Ação</dt>
                    <dd><%= log.descricao %></dd>
                    <dt>Data</dt>
                    <dd><%= log.created_at.strftime('%d/%m/%Y ás %H:%M') %></dd>
                  </dl>
              <% end %>
            </ul>
        <% else %>
            <div class="alert alert-info fill">
              <p>Parece que nenhuma sugestão foi feita a este ensalamento.</p>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ensalamentos/solicitados.html.erb
<h2><i class="fa fa-compass"></i> &nbsp;Ensalamentos solicitados</h2>
<hr>
<% if notice %>
    <div class="alert alert-success fill">
      <button type="button" class="close" data-dismiss="alert">
        ×
      </button>
      <%= notice %>
    </div>
<% end %>
<p>
  <%= link_to 'Solicitar Ensalamento', new_ensalamento_path, class: 'btn btn-primary' %>
</p>
<% if @ensalamentos.any? %>
    <table class="table table-hover" style="margin-top: 10px">
      <thead>
      <tr>
        <th>Perídodo</th>
        <th>Disciplina</th>
        <th width="140">Qtd. de Alunos</th>
        <th>Sala</th>
        <th class="text-center" width="70"><i class="fa fa-cogs"></i></th>
      </tr>
      </thead>

      <tbody>
      <% @ensalamentos.each do |ensalamento| %>
          <tr>
            <td><%= ensalamento.periodo.nome %></td>
            <td><%= ensalamento.disciplina.nome %></td>
            <td class="text-center"><%= ensalamento.alunos %></td>
            <td class="text-center"><%= ensalamento.sala ? ensalamento.sala.nome : '--' %></td>
            <td class="text-center">
              <div class="dropdown">
                <a class="btn btn-xs btn-default" data-toggle="dropdown">
                  <i class="fa fa-cog"></i><span class="caret"></span>
                </a>
                <ul class="dropdown-menu text-left">
                  <li role="presentation"><%= link_to ensalamento_path(ensalamento) do %>
                        <i class="fa fa-folder-open-o"></i> Detalhes
                    <% end %></li>
                  <li role="presentation"><%= link_to ensalamento_sugestoes_path(ensalamento) do %>
                        <i class="fa fa-plus-square-o"></i> Sugestões
                    <% end %></li>
                  <% unless ensalamento.final %>
                      <li role="presentation"><%= link_to ensalamento, method: :delete, data: {confirm: 'Deseja realmente remover esta sugestão de ensalamento?'} do %>
                            <i class="fa fa-trash-o"></i> Remover
                        <% end %></li>
                  <% end %>
                </ul>
              </div>


            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info">
      Parece que você ainda não solicitou nenhum ensalamento.
    </div>
<% end %>