config/routes.rb
Rails.application.routes.draw do

  scope path_names: {new: 'solicitar', edit: 'efetuar'} do
    resources :ensalamentos do

      resources :sugestoes, only: [:index, :new, :create, :destroy], path_names: {new: 'novo'}

      collection do
        get 'solicitados'
        get 'abertos'
        get 'fechados'
      end
    end

    resources :reservas do
      collection do
        get 'solicitadas'
        get 'abertas'
        get 'fechadas'
      end
    end
  end

  scope path_names: {new: 'novo', edit: 'editar'} do
    scope 'ensalamentos/configuracao' do
      resources :predios, :salas, :periodos, except: :show
    end

    scope 'admin' do
      resources :usuarios, except: :show
    end

    resources :cursos, except: :show do
      resources :disciplinas, except: :show
    end

    resources :espacos
  end

  root 'index#index'

  get 'ensalamentos/relatorios/:periodo', controller: 'ensalamentos', action: 'relatorios', as: :relatorios

  get 'login', controller: 'index', action: 'login'
  post 'login', controller: 'index', action: 'logar'
  get 'logout', controller: 'index', action: 'logout'

  get '*path' => redirect('/')

end

app/models/curso.rb
class Curso < ActiveRecord::Base
  belongs_to :coordenador, class_name: 'Usuario'

  has_many :disciplinas, dependent: :restrict_with_error
  has_many :usuarios, dependent: :restrict_with_error

  validates :nome, presence: {message: '^Nome do curso não pode estar vazio.'}
end

app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
  belongs_to :curso
  belongs_to :professor, class_name: 'Usuario'

  has_many :ensalamentos

  validates :nome, presence: {message: '^O campo nome não pode estar vazio.'}
end

app/models/ensalamento.rb
class Ensalamento < ActiveRecord::Base
  belongs_to :disciplina
  belongs_to :sala
  belongs_to :periodo
  belongs_to :deferente, class_name: 'Usuario', inverse_of: :deferimentos
  belongs_to :solicitante, class_name: 'Usuario', inverse_of: :solicitacoes

  has_many :logs, as: :loggable
  has_many :sugestoes

  validates :disciplina_id, presence: {message: '^O campo disciplina não pode estar vazio.'}
  validates :alunos, presence: {message: '^A quantidade de alunos não pode estar vazia.'}
  validates :periodo_id, presence: {message: '^O campo período não pode estar vazio.'}
end

app/models/espaco.rb
class Espaco < ActiveRecord::Base
  has_many :reservas

  def to_s
    self.nome
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :loggable, polymorphic: true
end

app/models/periodo.rb
class Periodo < ActiveRecord::Base
  has_many :ensalamentos

  validates :nome, presence: {message: '^Nome do período não pode estar vazio.'}
end

app/models/predio.rb
class Predio < ActiveRecord::Base
  has_many :salas, dependent: :restrict_with_error

  validates :nome, presence: {message: '^Nome do prédio não pode estar vazio.'}
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
  belongs_to :solicitante, class_name: 'Usuario'
  belongs_to :deferente, class_name: 'Usuario'
  belongs_to :espaco

  has_many :logs, as: :loggable
end

app/models/sala.rb
class Sala < ActiveRecord::Base
  belongs_to :predio

  has_many :ensalamentos
  has_many :sugestoes

  validates :nome, presence: {message: '^Nome da sala não pode estar vazio.'}
  validates :numero, presence: {message: '^Número da sala não pode estar vazio.'}
  validates :predio_id, presence: {message: '^É preciso que se selecione um prédio para a sala.'}
  validates :capacidade, presence: {message: '^Capacidade da sala não pode estar vazia.'}

  def self.ensalaveis(ensalamento)
    salas_usadas = Ensalamento.where('periodo_id = ? AND sala_id IS NOT NULL', ensalamento.periodo_id).pluck(:sala_id)
    where(
        'capacidade >= ? AND (id NOT IN (?) OR id = ?)',
        ensalamento.alunos,
        salas_usadas.any? ? salas_usadas : '',
        ensalamento.sala_id
    )
  end
end

app/models/sugestao.rb
class Sugestao < ActiveRecord::Base
  belongs_to :ensalamento
  belongs_to :sala

  has_many :logs, as: :loggable
end

app/models/tipo_usuario.rb
class TipoUsuario < ActiveRecord::Base
  has_many :usuarios, dependent: :restrict_with_error
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :tipo_usuario
  belongs_to :curso

  has_many :disciplinas, dependent: :restrict_with_error
  has_many :logs, dependent: :restrict_with_error
  has_many :deferimentos, class_name: 'Ensalamento', inverse_of: :deferente, foreign_key: 'deferente_id'
  has_many :solicitacoes, class_name: 'Ensalamento', inverse_of: :solicitante, foreign_key: 'solicitante_id'
  has_many :cursos

  has_many :reservas_solicitadas, class_name: 'Reserva', inverse_of: :solicitante
  has_many :reservas_efetuadas, class_name: 'Reserva', inverse_of: :deferente

  validates :nome, presence: {message: '^Nome do usuário não pode estar vazio.'}
  validates :cgu, presence: {message: '^Número do CGU não pode estar vazio.'}
  validates :curso_id, presence: {message: '^O campo curso não pode estar vazio para um coordenador de curso.'}, if: :coordenador?

  def coordenador?
    tipo_usuario_id == 2
  end
end

app/controllers/espacos_controller.rb
class EspacosController < ApplicationController
  before_action :set_espaco, only: [:show, :edit, :update, :destroy]
  before_action :check_acesso

  # GET /espacos
  # GET /espacos.json
  def index
    @espacos = Espaco.all
  end

  # GET /espacos/1
  # GET /espacos/1.json
  def show
  end

  # GET /espacos/new
  def new
    @espaco = Espaco.new
  end

  # GET /espacos/1/edit
  def edit
  end

  # POST /espacos
  # POST /espacos.json
  def create
    @espaco = Espaco.new(espaco_params)

    respond_to do |format|
      if @espaco.save
        format.html { redirect_to espacos_path, notice: 'Espaço criado com sucesso.' }
        format.json { render :show, status: :created, location: @espaco }
      else
        format.html { render :new }
        format.json { render json: @espaco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /espacos/1
  # PATCH/PUT /espacos/1.json
  def update
    respond_to do |format|
      if @espaco.update(espaco_params)
        format.html { redirect_to espacos_path, notice: 'Espaço atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @espaco }
      else
        format.html { render :edit }
        format.json { render json: @espaco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /espacos/1
  # DELETE /espacos/1.json
  def destroy
    @espaco.destroy
    respond_to do |format|
      format.html { redirect_to espacos_url, notice: 'Espaço removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_espaco
    @espaco = Espaco.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def espaco_params
    params.require(:espaco).permit(:nome)
  end

  def check_acesso
    redirect_to root_path unless @activeUser.tipo_usuario_id.in? [5, 3]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/espacos_helper.rb
module EspacosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/periodos_helper.rb
module PeriodosHelper
end

app/helpers/predios_helper.rb
module PrediosHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/salas_helper.rb
module SalasHelper
end

app/helpers/sugestoes_helper.rb
module SugestoesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/espacos/_form.html.erb
<%= form_for(@espaco) do |f| %>
    <% if @espaco.errors.any? %>
        <div class="alert alert-danger fill">
            <h4><%= pluralize(@espaco.errors.count, 'erro impediu', 'erros impediram') %> este espaço de ser salvo.</h4>

            <ul>
                <% @espaco.errors.full_messages.each do |message| %>
                    <li><small><%= message %></small></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <hr>
    <div class="row">
        <div class="col col-xs-12 form-group">
            <%= f.label :nome %>
            <br>
            <%= f.text_field :nome, class: 'form-control' %>
        </div>
    </div>
    <hr>
    <div class="actions" style="margin-bottom: 50px">
        <%= f.submit 'Salvar', class: 'btn btn-primary pull-left' %>
        <%= link_to 'Voltar', periodos_path, class: 'btn btn-default pull-right' %>
    </div>
<% end %>

app/views/espacos/edit.html.erb
<h2>Editando espaço</h2>

<%= render 'form' %>

app/views/espacos/index.html.erb
<h2><i class="fa fa-building-o"></i> &nbsp;Espaços</h2>
<hr>
<% if notice %>
    <div class="alert alert-success fill">
        <button type="button" class="close" data-dismiss="alert">
            ×
        </button>
        <%= notice %>
    </div>
<% end %>
<p>
    <%= link_to 'Adicionar Espaço', new_espaco_path, class: 'btn btn-primary' %>
</p>
<% if @espacos.any? %>
    <table class="table table-hover" style="margin-top: 10px">
        <thead>
        <tr>
            <th>Nome</th>
            <th class="text-center" width="70"><i class="fa fa-cogs"></i></th>
        </tr>
        </thead>

        <tbody>
        <% @espacos.each do |espaco| %>
            <tr>
                <td><%= espaco.nome %></td>
                <td class="text-center">
                    <div class="dropdown">
                        <a class="btn btn-xs btn-default" data-toggle="dropdown">
                            <i class="fa fa-cog"></i><span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu text-left">
                            <li role="presentation"><%= link_to edit_espaco_path(espaco) do %>
                                    <i class="fa fa-edit"></i> Editar
                                <% end %></li>
                            <li role="presentation"><%= link_to espaco, method: :delete, data: {confirm: 'Deseja realmente remover este espaço?'} do %>
                                    <i class="fa fa-trash-o"></i> Remover
                                <% end %></li>
                        </ul>
                    </div>


                </td>
            </tr>
        <% end %>
        </tbody>
    </table>
<% else %>
    <div class="alert alert-info">
        Parece que ainda não existe nenhum espaço cadastrado.
    </div>
<% end %>

app/views/espacos/new.html.erb
<h2>Novo espaço</h2>

<%= render 'form' %>

app/views/espacos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @espaco.nome %>
</p>

<%= link_to 'Edit', edit_espaco_path(@espaco) %> |
<%= link_to 'Back', espacos_path %>